-- AlterTable
ALTER TABLE "FoodItem" ADD COLUMN     "baseAmount" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "carbG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fatG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "unitLabel" TEXT NOT NULL DEFAULT 'g',
ADD COLUMN     "unitType" TEXT NOT NULL DEFAULT 'gram';

-- AlterTable
ALTER TABLE "Meal" ADD COLUMN     "carbG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fatG" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "MealPreset" ADD COLUMN     "carbG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fatG" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "carbTargetG" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "fatTargetG" INTEGER NOT NULL DEFAULT 70;
